language: cpp

compiler:
  - clang
  - gcc

before_script:
  - ./autogen.sh
before_install:
  - eval "${MATRIX_EVAL}"

addons:
  apt:
    packages:
      - libc++-dev

# TODO: test different combinations of flags, --enable-sdl, --enable-qt, etc
script:
  - ./configure $PM_OPTS --prefix=$PWD/local && make -j6 && make install  # build from checkout
  - make dist && tar -zxf projectM-*.tar.gz && cd projectM-* && ./configure $PM_OPTS --prefix=$PWD/dist_install && make -j6 && make install  # build from dist
  - echo "PWD=$PWD"
  - ls .
  # - test -e src/projectM-sdl/projectMSDL
  - test -e src/libprojectM/libprojectM.la
  - test -e dist_install/share/projectM/fonts/Vera.ttf
  - test -d dist_install/share/projectM/presets
  - test -e dist_install/lib/libprojectM.la
  - test -e dist_install/include/libprojectM/projectM.hpp
  - test -e dist_install/include/libprojectM/Common.hpp
  - test -e dist_install/include/libprojectM/PCM.hpp
  - dist_install/bin/projectM-unittest

# test on GCC and Clang
matrix:
  include:
    # SDL
    - os: linux
      addons:
        apt:
          packages:
            - libsdl2-dev
            - libglm-dev
      env:
        - MATRIX_EVAL="PM_OPTS=\"--enable-sdl\""

    #  pulseaudio/qt/jack
    - os: linux
      addons:
        apt:
          packages:
            - libsdl2-dev
            - libglm-dev
            - qt5-default
            - qtdeclarative5-dev
            - libqt5opengl5-dev
            - libjack-dev
            - libpulse-dev
            - libsdl-dev  # for jack
      env:
        - MATRIX_EVAL="PM_OPTS=\"--enable-qt --enable-jack --enable-pulseaudio\""

    # osx/xcode/clang
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew update && brew install sdl2 glm"

notifications:
  email:
    on_success: never
    on_failure: change
